AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CRMEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access to CRM Service
      VpcId: vpc-00fcba0619ae65a37 # Replace with your VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  EC2ECRAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECRAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:BatchGetImage
                Resource: "*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2ECRAccessRole

  CrmEC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: CRMEC2SecurityGroup
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05b10e08d247fb927  # Replace with latest Amazon Linux 2 AMI
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - !Ref CRMEC2SecurityGroup

  CRMDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: crm-db
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: postgres
      MasterUserPassword: Crmpwd123!
      PubliclyAccessible: false
      MultiAZ: false

  CRMCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: crm-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt CrmEC2Instance.PublicIp

  DatabaseEndpoint:
    Description: RDS Database Endpoint
    Value: !GetAtt CRMDatabase.Endpoint.Address

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CRMCognitoUserPool
